server.port=8086
spring.application.name=reportes

eureka.client.serviceUrl.defaultZone=http://192.168.210.229:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.compatibility-verifier.enabled=false