server.port=8086
spring.application.name=reportes

# Eureka (Apagado temporalmente para pruebas locales)
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false