server.port=8086
spring.application.name=reportes

eureka.client.serviceUrl.defaultZone=http://26.87.230.97:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.enabled=true

spring.cloud.compatibility-verifier.enabled=false